import Head from 'next/head'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bgMain}>
        <h1>
          Lorenzo Durante
        </h1>
        <h4>
          19 year old frontend developer, React developer and computer science student based in Buenos Aires, Argentina.
        </h4>
      </div>
    </>
  )
}
