import Head from 'next/head'
import styles from '../styles/Home.module.scss'


export default function Home() {
  const t = "hola"
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bgMain}>
        <h1>
          I'm a developer specializing in frontend development. 
        </h1>
      </div>
    </>
  )
}
